---
# Configuring apple Time Machine service

- name: Create Time Machine install script
  copy:
     src: tm.sh
     dest: /tmp/tm.sh
     owner: root
     group: root
     mode: 0755
  tags: tm

- name: Run command to install Time Machine on WebDav mount point
  command: bash /tmp/tm.sh
  become: true
  tags: tm

- name: Create Time Machine test file
  file:
     path: /opt/tm.test
     state: touch
     owner: root
     group: root
     mode: 0644
  tags: tm

